spring.application.name=ContatoDao
debug=true
spring.datasource.url=jdbc:postgresql://localhost:5432/Teste
spring.datasource.username=discente
spring.datasource.password=discente
spring.datasource.driver-class-name=org.postgresql.Driver

